name: secrets using env

on:
  push

jobs:
  firstjob:
    runs-on:
      ubuntu-latest

    steps:
      - name: first jobs
        run: echo "hello world"

      - name: install ssh
        run: sudo apt update && sudo apt install -y sshpass

      - name: ssh into the server
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}

        run: |
          sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no "$USER"@"$HOST" << 'EOF'
          pwd
          ls -al
          EOF
