name: checktheworkflow

on:
  push

jobs:
  firstjob:
    runs-on:
      ubuntu-latest

    steps:
      - name: first jobs
        run: echo "hello world"

      - name: install ssh
        run: sudo apt update && sudo apt install -y sshpass

      - name: ssh into the server
        run: |
          sshpass -p ${{ secrets.PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} << 'EOF'
          pwd
          ls -al
          EOF