name: checktheworkflow

on:
  push

jobs:
  firstjob:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: first job
        run: echo "hello world"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build frontend
        run: |
          echo "FRONT=${{ secrets.FRONT }}" > .env
          echo "SECOND=${{ secrets.SECOND }}" >> .env
          echo "MUTHU=${{ secrets.MUTHU }}" >> .env
          cat .env
          pwd
          ls -al

